import { useState } from "react";
import { Link } from "@tanstack/react-router";
import { motion } from "framer-motion";
import { ArrowRight, Send } from "lucide-react";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import { PublicHeader } from "@/components/layout/PublicHeader";
import { InfoFooter } from "@/components/layout/InfoFooter";
export function KontakPage() { const [form, setForm] = useState({ name: "", email: "", message: "" }); const [busy, setBusy] = useState(false); const submit = (event) => { event.preventDefault(); setBusy(true); setTimeout(() => { setBusy(false); setForm({ name: "", email: "", message: "" }); toast.success("Pesanmu terkirim. Kami membalas pelan-pelan — maksimal 2 hari kerja."); }, 650); }; return <div className="public-page"><PublicHeader /><main className="info-page page-container" data-testid="contact-page"><motion.div className="info-hero" initial={{ opacity: 0, y: 26 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6, ease: "easeOut" }}><span className="eyebrow">Kontak</span><h1>Kamu boleh mengetuk, <em>pelan-pelan.</em></h1><p>Punya pertanyaan, masukan, atau butuh bantuan teknis? Tulis pesan — tim kami membacanya dengan hati-hati.</p></motion.div><div className="contact-grid" data-testid="contact-grid"><div className="contact-info"><div className="contact-card"><span className="eyebrow">Email</span><a href="mailto:halo@titikjiwa.id" data-testid="contact-email-link">halo@titikjiwa.id</a><span>Untuk pertanyaan umum dan kemitraan.</span></div><div className="contact-card"><span className="eyebrow">Situasi darurat</span><a href="tel:112" data-testid="contact-emergency-link">112</a><span>Jika keselamatanmu atau orang lain terancam, hubungi segera — jangan menunggu balasan di sini.</span></div><div className="contact-card"><span className="eyebrow">Jam respons</span><strong>Senin–Jumat, 09.00–17.00 WIB</strong><span>Pesan di luar jam dibalas pada hari kerja berikutnya.</span></div></div><form className="composer-card contact-form" onSubmit={submit} data-testid="contact-form"><div className="composer-heading"><div><span className="eyebrow">Tulis pesan</span><h2>Ceritakan yang ingin kamu sampaikan.</h2></div></div><label>Nama<Input value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Nama panggilanmu" required data-testid="contact-name-input" /></label><label>Email<Input type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="email@contoh.com" required data-testid="contact-email-input" /></label><label>Pesan<Textarea value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })} placeholder="Tulis dengan tenang…" rows={5} required data-testid="contact-message-input" /></label><button className="button button-primary" disabled={busy} data-testid="contact-submit-button">{busy ? "Mengirim…" : "Kirim pesan"}<Send size={15} /></button></form></div><div className="info-cta"><Link to="/masuk" className="button button-primary" data-testid="contact-cta-button">Kembali ke ruang pulih <ArrowRight size={16} /></Link></div></main><InfoFooter /></div>; }

export function InfoPage({ eyebrow, title, lede, sections }) { return <div className="public-page"><PublicHeader /><main className="info-page page-container" data-testid="info-page"><motion.div className="info-hero" initial={{ opacity: 0, y: 26 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .6, ease: "easeOut" }}><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{lede}</p></motion.div><div className="info-sections">{sections.map((section, index) => <motion.section className="info-section" key={section.heading} initial={{ opacity: 0, y: 22 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true, margin: "-60px" }} transition={{ duration: .55, delay: (index % 3) * .08 }} data-testid={`info-section-${index}`}><span className="info-number">{String(index + 1).padStart(2, "0")}</span><h2>{section.heading}</h2><p>{section.body}</p></motion.section>)}</div><div className="info-cta"><Link to="/masuk" className="button button-primary" data-testid="info-cta-button">Mulai pelan-pelan <ArrowRight size={16} /></Link></div></main><InfoFooter /></div>; }

export function FeaturesPage() { return <InfoPage eyebrow="Fitur titikjiwa" title="Semua yang kamu butuhkan untuk pulih, dalam satu ruang." lede="Setiap fitur dirancang dengan satu prinsip: tidak ada yang terburu-buru, tidak ada yang dihakimi." sections={[{ heading: "Jurnal pribadi", body: "Tulis yang belum sempat terucap. Terkunci hanya untukmu, ditemani prompt refleksi harian dan rekap suasana hati mingguan." }, { heading: "Linimasa publik anonim", body: "Bagikan pengalaman tanpa nama. Pilih jenis dukungan yang kamu butuhkan, terima pelukan dan kekuatan dari orang yang paham." }, { heading: "Teman AI yang belajar", body: "Teman AI menjawab kata demi kata, mengenalmu dari wawancara singkat, dan terus belajar dari pengalaman komunitas serta panduan psikolog." }, { heading: "Insight mingguan", body: "Setiap minggu, pola perasaanmu dirangkum menjadi satu catatan lembut — tersimpan sebagai linimasa pertumbuhanmu." }, { heading: "Psikolog terverifikasi", body: "Baca panduan mereka, kenali pendekatannya, dan ajukan konsultasi gratis dengan satu ketukan." }, { heading: "Ruang yang dijaga", body: "Konten sensitif ditandai, laporan ditinjau admin, dan akun psikolog dikelola dengan teliti demi keamanan bersama." }]} />; }

export function TutorialPage() { return <InfoPage eyebrow="Tutorial" title="Enam langkah pertamamu di titikjiwa." lede="Tidak perlu semua sekaligus. Mulai dari langkah yang paling ringan hari ini." sections={[{ heading: "Daftar dengan nama samaran", body: "Cukup email dan nama samaran. Email hanya untuk akses akun — di komunitas, kamu selalu Anonim." }, { heading: "Isi wawancara singkat", body: "Tiga pertanyaan pengenalan. Bisa dilewati, tetapi jawabannya membantu Teman AI dan ruang ini memahami caramu." }, { heading: "Tulis jurnal pertamamu", body: "Satu kalimat pun cukup. Jika buntu, gunakan prompt harian — lalu lihat pola suasana hatimu terangkum dari minggu ke minggu." }, { heading: "Baca dan berbagi di Linimasa", body: "Temukan cerita yang terasa dekat. Saat berbagi, pilih jenis dukungan yang kamu harapkan agar respons yang datang tepat." }, { heading: "Ngobrol dengan Teman AI", body: "Tiga saran pembuka yang personal menantimu. Balasannya mengalir kata demi kata, seperti bercerita pada teman." }, { heading: "Ajukan konsultasi", body: "Buka direktori psikolog, pilih yang terasa cocok, tulis kebutuhanmu — mereka akan mengonfirmasi dari dasbornya." }]} />; }

export function PrivacyPage() { return <InfoPage eyebrow="Privasi" title="Ceritamu milikmu. Titik." lede="Kami merancang titikjiwa dengan asumsi bahwa setiap huruf yang kamu tulis adalah kepercayaan." sections={[{ heading: "Yang kami simpan", body: "Email untuk akses akun, nama samaran, jawaban wawancara, dan tulisan yang kamu buat. Tidak ada data lain yang kami kumpulkan diam-diam." }, { heading: "Jurnal tetap milikmu", body: "Jurnal pribadi tidak dibaca siapa pun, tidak dibagikan, dan tidak dipakai sebagai bahan belajar AI. Hanya kamu yang bisa membukanya." }, { heading: "Anonimitas linimasa", body: "Cerita yang kamu bagikan tampil tanpa identitas. Tidak ada nama asli, email, atau jejak akun yang terlihat pengguna lain." }, { heading: "Teman AI dan data", body: "AI belajar dari konten yang memang dibagikan publik dan percakapanmu dengannya — disimpan untuk melanjutkan konteks, bukan untuk dijual." }, { heading: "Email dan sesi", body: "Email hanya dipakai untuk pemulihan kata sandi. Sesi memakai cookie terenkripsi httpOnly tanpa pelacak iklan." }, { heading: "Hakmu", body: "Kamu boleh meminta penghapusan akun dan seluruh datamu kapan saja. Ruang ini tidak menahan siapa pun." }]} />; }

export function TermsPage() { return <InfoPage eyebrow="Syarat & Ketentuan" title="Aturan main yang menjaga semua orang." lede="Ketentuan ini ada agar ruang ini tetap aman untuk mereka yang sedang rapuh." sections={[{ heading: "Bukan layanan medis", body: "titikjiwa adalah ruang dukungan dan edukasi. Konten dan Teman AI bukan pengganti diagnosis, terapi, atau penanganan profesional." }, { heading: "Situasi darurat", body: "Jika kamu atau orang lain dalam bahaya, segera hubungi layanan darurat setempat atau orang yang kamu percaya. Jangan menunggu balasan di sini." }, { heading: "Etika komunitas", body: "Tanpa penghakiman, tanpa promosi, tanpa merendahkan pengalaman orang lain. Dukung dengan kehadiran, bukan dengan memperbaiki." }, { heading: "Konten sensitif", body: "Tandai cerita yang berat dengan jujur agar pembaca bisa memilih kesiapannya. Laporan penyalahgunaan akan ditinjau admin." }, { heading: "Peran psikolog", body: "Psikolog di titikjiwa berbagi panduan umum dan pendampingan awal. Konsultasi formal mengikuti ketentuan praktik masing-masing." }, { heading: "Perubahan ketentuan", body: "Jika ketentuan berubah, kami mengumumkannya di dalam aplikasi. Melanjutkan penggunaan berarti menyetujui versi terbaru." }]} />; }
